<a href="https://colab.research.google.com/github/kukretinishtha/Mathematics/blob/main/Mathematics_Statistics_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math

In [2]:
# Getting the value of cos
math.cos( 0 )

1.0

In [3]:
# Getting thevalue of exp
math.exp( 1 )

2.718281828459045

In [ ]:
# Mathematical value of Natural log
math.log( 10 )

In [ ]:
# Getting distance between two points used in python 3.8 or +
x = math.dist([1,0], [-5,2])

**Quadratic Formula Definition**

In [13]:
def quadratic_formula_1 ( a, b, c ):
    solution1 = ( -b + ( b**2 - 4*a*c )**0.5 ) / ( 2*a )
    solution2 = ( -b - ( b**2 - 4*a*c )**0.5 ) / ( 2*a )
    return ( solution1, solution2 )

quadratic_formula_1(3,-9,6)

(2.0, 1.0)

In [14]:
def quadratic_formula_2 ( x_squared_coefficient, x_coefficient, constant ):
    solution1 = ( -x_coefficient + \
                    ( x_coefficient**2 - 4*x_squared_coefficient*constant )**0.5 ) \
                  / ( 2*x_squared_coefficient )
    solution2 = ( -x_coefficient - \
                    ( x_coefficient**2 - 4*x_squared_coefficient*constant )**0.5 ) \
                  / ( 2*x_squared_coefficient )
    return ( solution1, solution2 )


quadratic_formula_2(3,-9,6)

(2.0, 1.0)

**Normal Probability Distribution Function**

In [15]:
def normal_pdf ( μ, σ, x ):
    """The value of the probability density function for
    the normal distribution N(μ,σ^2), with mean μ and
    variance σ^2."""
    shifted = ( x - μ ) / σ
    return math.exp( -shifted**2 / 2.0 ) \
         / math.sqrt( 2*math.pi ) / σ

normal_pdf( 10, 2, 15 )

0.00876415024678427

**Numpy Operations**

In [16]:
import numpy as np
values = np.random.rand( 30 )
values

array([0.37169532, 0.30819655, 0.22192087, 0.51109833, 0.64555519,
       0.22211958, 0.18445554, 0.7162821 , 0.98187318, 0.44546403,
       0.95006398, 0.58705159, 0.25820216, 0.84809872, 0.81852171,
       0.78270608, 0.537419  , 0.66415411, 0.18788239, 0.38393392,
       0.45628441, 0.26168831, 0.64277135, 0.8303666 , 0.12655494,
       0.30372628, 0.83213844, 0.79052187, 0.2386933 , 0.37299652])

In [17]:
np.around( values, 2 )

array([0.37, 0.31, 0.22, 0.51, 0.65, 0.22, 0.18, 0.72, 0.98, 0.45, 0.95,
       0.59, 0.26, 0.85, 0.82, 0.78, 0.54, 0.66, 0.19, 0.38, 0.46, 0.26,
       0.64, 0.83, 0.13, 0.3 , 0.83, 0.79, 0.24, 0.37])

In [18]:
np.exp( values )

array([1.45019106, 1.36096846, 1.24847259, 1.66712125, 1.90704551,
       1.24872069, 1.20256351, 2.04680922, 2.66945192, 1.56121448,
       2.5858751 , 1.79867736, 1.29460051, 2.33520275, 2.26714587,
       2.18738349, 1.71158356, 1.94284639, 1.20669159, 1.46804843,
       1.57819914, 1.29912155, 1.90174397, 2.29415964, 1.13491181,
       1.35489815, 2.29822812, 2.20454661, 1.26958909, 1.45207929])

In [19]:
np.square( values )

array([0.13815741, 0.09498511, 0.04924887, 0.26122151, 0.4167415 ,
       0.04933711, 0.03402385, 0.51306005, 0.96407494, 0.1984382 ,
       0.90262157, 0.34462957, 0.06666836, 0.71927144, 0.6699778 ,
       0.6126288 , 0.28881919, 0.44110068, 0.03529979, 0.14740526,
       0.20819546, 0.06848077, 0.413155  , 0.6895087 , 0.01601615,
       0.09224966, 0.69245439, 0.62492482, 0.05697449, 0.1391264 ])

**RMSSE**

In [20]:
ys    = np.array( [ 1, 2, 3, 4, 5 ] )   # made up data
yhats = np.array( [ 2, 1, 0, 3, 4 ] )   # also made up
RSSE  = np.sqrt( np.sum( np.square( ys - yhats ) ) )
RSSE

3.605551275463989

**Argument Binding Function**

In [21]:
from functools import partial
'''
To get the standard normal distribution, fill in the values μ=0 and σ=1 once 
for all and then use that on as many x inputs
'''
my_pdf = partial( normal_pdf, 0, 1 )
my_pdf( 0 ), my_pdf( 1 ), my_pdf( 2 ), my_pdf( 3 ), my_pdf( 4 )

(0.3989422804014327,
 0.24197072451914337,
 0.05399096651318806,
 0.0044318484119380075,
 0.00013383022576488537)

In [23]:
# Random number generating procedures
import scipy.stats as stats
stats.uniform.rvs( 0, 100, size=10 )

array([ 3.22148222, 95.500811  , 14.73716601, 56.04280536, 93.14051993,
       30.53978992, 80.78888155,  3.10831988, 41.89545997, 41.29624867])

In [24]:
X = stats.uniform( 0, 100 )  # make a random variable
X.rvs( size=10 )             # generate 10 values from it

array([65.21866466, 69.49511848, 99.01719962, 25.95829749, 84.63956559,
       19.53521719, 63.59250708,  4.43274064, 87.17596375, 87.39131741])

In [25]:
# For binding the second argument partial tool does not work.
# We need to use lambda function for that.
def subtract ( a, b ):  
    return a - b

subtract_1 = lambda a: subtract( a, 1 )  # bind second argument to 1

subtract_1( 5 )

4